### ISSUE TITLE
How could we get the realtion between GPT-3/T5 and orginal text?

### ISSUE THREAD

**Issue by fengsxy** [jpwahle/emnlp22-transforming#1]
I have seen the dataset, it has the oginal, GPT, T5. But i couldn't find the orignal text and its paraprased sentences. Is it possible to find the mapping relationship？

**Comment by jpwahle** [comment]
Hi there, sure we will add the ids of the source document to each paraphrase pair. Since the final task is single-sentence classification, we did not include them in the 🤗 HF dataset. Soon there will be another release on zenodo similar to this one [here](https://zenodo.org/record/3608000) in which all ids are present.

**Comment by fengsxy** [comment]
> Hi there, sure we will add the ids of the source document to each paraphrase pair. Since the final task is single-sentence classification, we did not include them in the 🤗 HF dataset. Soon there will be another release on zenodo similar to this one [here](https://zenodo.org/record/3608000) in which all ids are present.

Thank you for you reply. I have reviewed the proposed url. I am confused that why the original's number is not equal to the paraphrased number.

**Comment by jpwahle** [comment]
Hi there 👋🏻
In the dataset that I sent, we don't have aligned examples. We extracted all paragraphs from the article (e.g., arXiv) and paraphrased ~50% with either method. Therefore, in this case, the number of paraphrases and originals is not exactly equal (but certainly similar).
In other datasets, we did it differently, and the amount is exactly equal.
I hope this answers your question. Let me know if I can support you further in using the datasets.

**Comment by fengsxy** [comment]
> Hi there 👋🏻 In the dataset that I sent, we don't have aligned examples. We extracted all paragraphs from the article (e.g., arXiv) and paraphrased ~50% with either method. Therefore, in this case, the number of paraphrases and originals is not exactly equal (but certainly similar). In other datasets, we did it differently, and the amount is exactly equal. I hope this answers your question. Let me know if I can support you further in using the datasets.

Thank you for your patient answer. I am very looking forward to this dataset. Beacuse i am inspired by your paper and want to try a relevant work. Therefore, i want to ask for the date about public the GPT mapping paraphrase dataset.  And would the dataset divided into arxiv/wiki/... Or they just have been mixed together.

And i have another question, i find that prompt in your paper has "change the passage structure",  i have do similar experiment on GPT-3(Fine-tune it to paraphrase), but it couldn't be as strong as i image.  So would the prompt "change the passage structure" work in your experiment?

**Comment by fengsxy** [comment]
Hello, have the new dataset been provided? Because the GPT-3 generated text has high quality and costs a lot. 🤗

> Hi there, sure we will add the ids of the source document to each paraphrase pair. Since the final task is single-sentence classification, we did not include them in the 🤗 HF dataset. Soon there will be another release on zenodo similar to this one [here](https://zenodo.org/record/3608000) in which all ids are present.
